{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: routing-host
data:
  host: {{ .Values.ingress.application.host | quote }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fabric.fullname" . }}-api
  labels:
    {{- include "fabric.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tlsSecretName }}
  tls:
    - hosts: [{{ $.Values.ingress.application.host | quote }}]
      secretName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.application.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.api.externalPrefix }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "fabric.fullname" . }}-api
                port:
                  number: {{ .Values.services.api.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fabric.fullname" . }}-frontend
  labels:
    {{- include "fabric.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tlsSecretName }}
  tls:
    - hosts: [{{ $.Values.ingress.application.host | quote }}]
      secretName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.application.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.frontend.externalPrefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "fabric.fullname" . }}-frontend
                port:
                  number: {{ .Values.services.frontend.port }}
{{- end }}
