apiVersion: v1
kind: Secret
metadata:
  name: {{include "fabric.fullname" .}}-secrets
  labels:
    {{- include "fabric.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.global.serviceAuthSecret }}
  service-auth-secret: {{. | b64enc | quote}}
  {{- else }}
  service-auth-secret: {{randAlphaNum 64 | b64enc | quote}}
  {{- end }}
  {{- with .Values.global.jwtSecret }}
  jwt-secret: {{. | b64enc | quote}}
  {{- else }}
  jwt-secret: {{randAlphaNum 64 | b64enc | quote}}
  {{- end }}
