import os

# Files to skip (intentional domain-specific colors)
skip_files = {
    'apps/web/src/lib/entity-colors.tsx',
}

# Color replacements
replacements = [
    ('text-gray-400', 'text-muted-foreground'),
    ('text-gray-500', 'text-muted-foreground'),
    ('text-gray-600', 'text-muted-foreground'),
    ('text-gray-700', 'text-foreground'),
    ('text-gray-800', 'text-foreground'),
    ('text-gray-900', 'text-foreground'),
    ('bg-gray-50', 'bg-muted/50'),
    ('bg-gray-100', 'bg-muted'),
    ('bg-gray-200', 'bg-muted'),
    ('bg-gray-300', 'bg-muted'),
    ('border-gray-200', 'border-border'),
    ('border-gray-300', 'border-border'),
    ('text-slate-400', 'text-muted-foreground'),
    ('text-slate-500', 'text-muted-foreground'),
    ('text-slate-600', 'text-muted-foreground'),
    ('text-slate-700', 'text-foreground'),
    ('text-slate-800', 'text-foreground'),
    ('text-slate-900', 'text-foreground'),
    ('bg-slate-50', 'bg-muted/50'),
    ('bg-slate-100', 'bg-muted'),
    ('bg-slate-200', 'bg-muted'),
    ('border-slate-200', 'border-border'),
    ('border-slate-300', 'border-border'),
    ('text-neutral-300', 'text-muted-foreground'),
    ('text-neutral-400', 'text-muted-foreground'),
    ('text-neutral-500', 'text-muted-foreground'),
    ('text-neutral-600', 'text-muted-foreground'),
    ('text-neutral-700', 'text-foreground'),
    ('text-neutral-800', 'text-foreground'),
    ('text-neutral-900', 'text-foreground'),
    ('bg-neutral-50', 'bg-muted/50'),
    ('bg-neutral-100', 'bg-muted'),
    ('bg-neutral-200', 'bg-muted'),
    ('border-neutral-200', 'border-border'),
    ('border-neutral-300', 'border-border'),
    ('text-blue-400', 'text-primary'),
    ('text-blue-500', 'text-primary'),
    ('text-blue-600', 'text-primary'),
    ('text-blue-700', 'text-primary'),
    ('text-blue-800', 'text-primary'),
    ('bg-blue-50', 'bg-primary/10'),
    ('bg-blue-100', 'bg-primary/10'),
    ('bg-blue-200', 'bg-primary/20'),
    ('border-blue-200', 'border-primary/20'),
    ('border-blue-300', 'border-primary/30'),
    ('text-red-400', 'text-destructive'),
    ('text-red-500', 'text-destructive'),
    ('text-red-600', 'text-destructive'),
    ('text-red-700', 'text-destructive'),
    ('text-red-800', 'text-destructive'),
    ('bg-red-50', 'bg-destructive/10'),
    ('bg-red-100', 'bg-destructive/10'),
    ('bg-red-200', 'bg-destructive/20'),
    ('border-red-200', 'border-destructive/20'),
    ('border-red-300', 'border-destructive/30'),
    ('text-green-400', 'text-success'),
    ('text-green-500', 'text-success'),
    ('text-green-600', 'text-success'),
    ('text-green-700', 'text-success'),
    ('text-green-800', 'text-success'),
    ('bg-green-50', 'bg-success/10'),
    ('bg-green-100', 'bg-success/10'),
    ('bg-green-200', 'bg-success/20'),
    ('border-green-200', 'border-success/20'),
    ('border-green-300', 'border-success/30'),
    ('text-emerald-400', 'text-success'),
    ('text-emerald-500', 'text-success'),
    ('text-emerald-600', 'text-success'),
    ('text-emerald-700', 'text-success'),
    ('text-emerald-800', 'text-success'),
    ('bg-emerald-50', 'bg-success/10'),
    ('bg-emerald-100', 'bg-success/10'),
    ('bg-emerald-200', 'bg-success/20'),
    ('border-emerald-200', 'border-success/20'),
    ('border-emerald-300', 'border-success/30'),
    ('text-amber-400', 'text-warning'),
    ('text-amber-500', 'text-warning'),
    ('text-amber-600', 'text-warning'),
    ('text-amber-700', 'text-warning'),
    ('text-amber-800', 'text-warning'),
    ('bg-amber-50', 'bg-warning/10'),
    ('bg-amber-100', 'bg-warning/10'),
    ('bg-amber-200', 'bg-warning/20'),
    ('border-amber-200', 'border-warning/20'),
    ('border-amber-300', 'border-warning/30'),
    ('text-yellow-400', 'text-warning'),
    ('text-yellow-500', 'text-warning'),
    ('text-yellow-600', 'text-warning'),
    ('text-yellow-700', 'text-warning'),
    ('text-yellow-800', 'text-warning'),
    ('bg-yellow-50', 'bg-warning/10'),
    ('bg-yellow-100', 'bg-warning/10'),
    ('bg-yellow-200', 'bg-warning/20'),
    ('border-yellow-200', 'border-warning/20'),
    ('border-yellow-300', 'border-warning/30'),
    ('text-orange-400', 'text-warning'),
    ('text-orange-500', 'text-warning'),
    ('text-orange-600', 'text-warning'),
    ('text-orange-700', 'text-warning'),
    ('text-orange-800', 'text-warning'),
    ('bg-orange-50', 'bg-warning/10'),
    ('bg-orange-100', 'bg-warning/10'),
    ('bg-orange-200', 'bg-warning/20'),
    ('border-orange-200', 'border-warning/20'),
    ('border-orange-300', 'border-warning/30'),
    ('text-violet-400', 'text-primary'),
    ('text-violet-500', 'text-primary'),
    ('text-violet-600', 'text-primary'),
    ('text-violet-700', 'text-primary'),
    ('text-violet-800', 'text-primary'),
    ('bg-violet-50', 'bg-primary/10'),
    ('bg-violet-100', 'bg-primary/10'),
    ('bg-violet-200', 'bg-primary/20'),
    ('border-violet-200', 'border-primary/20'),
    ('border-violet-300', 'border-primary/30'),
    ('text-purple-400', 'text-primary'),
    ('text-purple-500', 'text-primary'),
    ('text-purple-600', 'text-primary'),
    ('text-purple-700', 'text-primary'),
    ('text-purple-800', 'text-primary'),
    ('bg-purple-50', 'bg-primary/10'),
    ('bg-purple-100', 'bg-primary/10'),
    ('bg-purple-200', 'bg-primary/20'),
    ('border-purple-200', 'border-primary/20'),
    ('border-purple-300', 'border-primary/30'),
    ('text-indigo-400', 'text-primary'),
    ('text-indigo-500', 'text-primary'),
    ('text-indigo-600', 'text-primary'),
    ('text-indigo-700', 'text-primary'),
    ('text-indigo-800', 'text-primary'),
    ('bg-indigo-50', 'bg-primary/10'),
    ('bg-indigo-100', 'bg-primary/10'),
    ('bg-indigo-200', 'bg-primary/20'),
    ('border-indigo-200', 'border-primary/20'),
    ('border-indigo-300', 'border-primary/30'),
    ('text-cyan-400', 'text-info'),
    ('text-cyan-500', 'text-info'),
    ('text-cyan-600', 'text-info'),
    ('text-cyan-700', 'text-info'),
    ('text-cyan-800', 'text-info'),
    ('bg-cyan-50', 'bg-info/10'),
    ('bg-cyan-100', 'bg-info/10'),
    ('bg-cyan-200', 'bg-info/20'),
    ('border-cyan-200', 'border-info/20'),
    ('border-cyan-300', 'border-info/30'),
    ('text-teal-400', 'text-success'),
    ('text-teal-500', 'text-success'),
    ('text-teal-600', 'text-success'),
    ('text-teal-700', 'text-success'),
    ('text-teal-800', 'text-success'),
    ('bg-teal-50', 'bg-success/10'),
    ('bg-teal-100', 'bg-success/10'),
    ('bg-teal-200', 'bg-success/20'),
    ('border-teal-200', 'border-success/20'),
    ('border-teal-300', 'border-success/30'),
    ('text-pink-400', 'text-primary'),
    ('text-pink-500', 'text-primary'),
    ('text-pink-600', 'text-primary'),
    ('text-pink-700', 'text-primary'),
    ('text-pink-800', 'text-primary'),
    ('bg-pink-50', 'bg-primary/10'),
    ('bg-pink-100', 'bg-primary/10'),
    ('bg-pink-200', 'bg-primary/20'),
    ('border-pink-200', 'border-primary/20'),
    ('border-pink-300', 'border-primary/30'),
    ('text-rose-400', 'text-destructive'),
    ('text-rose-500', 'text-destructive'),
    ('text-rose-600', 'text-destructive'),
    ('text-rose-700', 'text-destructive'),
    ('text-rose-800', 'text-destructive'),
    ('bg-rose-50', 'bg-destructive/10'),
    ('bg-rose-100', 'bg-destructive/10'),
    ('bg-rose-200', 'bg-destructive/20'),
    ('border-rose-200', 'border-destructive/20'),
    ('border-rose-300', 'border-destructive/30'),
    ('text-lime-400', 'text-success'),
    ('text-lime-500', 'text-success'),
    ('text-lime-600', 'text-success'),
    ('text-lime-700', 'text-success'),
    ('text-lime-800', 'text-success'),
    ('bg-lime-50', 'bg-success/10'),
    ('bg-lime-100', 'bg-success/10'),
    ('bg-lime-200', 'bg-success/20'),
]

# Size replacements
size_replacements = [
    ('text-[48px]', 'text-5xl'),
    ('text-[36px]', 'text-4xl'),
    ('text-[32px]', 'text-3xl'),
    ('text-[28px]', 'text-2xl'),
    ('text-[24px]', 'text-xl'),
    ('text-[22px]', 'text-2xl'),
    ('text-[20px]', 'text-xl'),
    ('text-[18px]', 'text-lg'),
    ('text-[16px]', 'text-base'),
    ('text-[15px]', 'vf-text-body-l'),
    ('text-[14px]', 'vf-text-body-l'),
    ('text-[13px]', 'vf-text-body-m'),
    ('text-[12px]', 'vf-text-body-s'),
    ('text-[11px]', 'vf-text-caption'),
    ('text-[10px]', 'vf-text-micro'),
    ('text-[9px]', 'vf-text-micro'),
    ('text-[8px]', 'vf-text-micro'),
]

fixed = []
for root, dirs, files in os.walk('apps/web/src'):
    for fname in files:
        if not fname.endswith('.tsx') or fname.endswith('.test.tsx'):
            continue
        path = os.path.join(root, fname)
        if path in skip_files:
            continue
        with open(path, 'r', encoding='utf-8') as f:
            text = f.read()
        
        original = text
        for old, new in replacements:
            text = text.replace(old, new)
        for old, new in size_replacements:
            text = text.replace(old, new)
        
        if text != original:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(text)
            fixed.append(os.path.relpath(path, 'apps/web/src'))

print(f'Fixed {len(fixed)} files:')
for f in fixed:
    print(f'  {f}')
