import subprocess
from datetime import datetime

branches_out = subprocess.check_output(['git', 'branch', '-r', '--sort=-committerdate', '--format=%(refname:short)|%(committerdate:iso8601)']).decode('utf-8')

inventory = ["| Owner | Branch | Age (days) | Last commit date | Associated PR | Disposition | Notes |", "|---|---|---:|---|---|---|---|"]

now = datetime.now()

for line in branches_out.strip().split('\n'):
    if not line: continue
    parts = line.split('|')
    branch = parts[0].replace('origin/', '')
    date_str = parts[1]
    commit_date = datetime.strptime(date_str, '%Y-%m-%d %H:%M:%S %z')
    age = (now - commit_date.replace(tzinfo=None)).days
    
    owner = "Unowned"
    if '/' in branch:
        owner = branch.split('/')[0]
    
    disposition = "abandoned" if age > 30 else "active"
    if branch == 'main' or branch.startswith('release/'):
        disposition = "protected"
    
    inventory.append(f"| {owner} | {branch} | {age} | {commit_date.strftime('%Y-%m-%d')} | none | {disposition} | Generated by agent |")

with open('docs/governance/branch-inventory.md', 'w') as f:
    f.write("# Branch Inventory\n\n")
    f.write("\n".join(inventory))
    f.write("\n")
