---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: application
  namespace: value-fabric
spec:
  hosts:
    - __HOST__
  gateways:
    - value-fabric-gateway
  http:
    - match:
        - uri:
            prefix: /api/v1
      rewrite:
        uri: /v1
      route:
        - destination:
            host: api-gateway
            port:
              number: 8000
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend
            port:
              number: 3000
