"""Layer 4 Agent Runtime — public package surface."""

from __future__ import annotations

from .adapters import (
    InMemoryCheckpointAdapter,
    InMemoryMemoryAdapter,
    LangGraphWorkflowEngineAdapter,
    LegacyToolRegistryAdapter,
    ModelProviderBridge,
    PolicyAuthzPort,
    PostgresCheckpointAdapter,
    PostgresMemoryAdapter,
)
from .context import RuntimeContextVar, current_context, get_tenant_id, with_context
from .core import AgentRuntimeImpl
from .errors import (
    AgentRuntimeError,
    CheckpointConflictError,
    ProviderNotFoundError,
    RunNotFoundError,
    TenantRequiredError,
    ToolForbiddenError,
    WorkflowTypeNotFoundError,
)
from .events import (
    CHECKPOINT_SAVED,
    RUN_CANCELLED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_PAUSED,
    RUN_RESUMED,
    RUN_STARTED,
    TOOL_CALLED,
    TOOL_DENIED,
    EventSink,
    RuntimeEvent,
    RuntimeEventBus,
)
from .models import (
    AuthzDecision,
    Checkpoint,
    Message,
    ModelConfig,
    ModelResponse,
    ResumeRequest,
    RunEnvelope,
    RunRequest,
    RunResult,
    RunStatus,
    RunSummary,
    RuntimeContext,
    ToolCall,
    ToolDef,
    ToolResult,
    ToolSchema,
    WorkflowResult,
)
from .observability import RuntimeMetrics, find_stale_runs
from .ports import (
    AgentRuntime,
    AuthzPort,
    CheckpointPort,
    MemoryPort,
    ModelProviderPort,
    ToolRegistryPort,
    WorkflowEnginePort,
    WorkflowFactory,
)

__all__ = [
    "AgentRuntime",
    "AgentRuntimeError",
    "AgentRuntimeImpl",
    "AuthzDecision",
    "AuthzPort",
    "CHECKPOINT_SAVED",
    "Checkpoint",
    "CheckpointConflictError",
    "CheckpointPort",
    "EventSink",
    "InMemoryCheckpointAdapter",
    "InMemoryMemoryAdapter",
    "LangGraphWorkflowEngineAdapter",
    "LegacyToolRegistryAdapter",
    "Message",
    "ModelConfig",
    "ModelProviderBridge",
    "ModelProviderPort",
    "ModelResponse",
    "MemoryPort",
    "PolicyAuthzPort",
    "PostgresCheckpointAdapter",
    "PostgresMemoryAdapter",
    "ProviderNotFoundError",
    "RUN_CANCELLED",
    "RUN_COMPLETED",
    "RUN_FAILED",
    "RUN_PAUSED",
    "RUN_RESUMED",
    "RUN_STARTED",
    "ResumeRequest",
    "RunEnvelope",
    "RunNotFoundError",
    "RunRequest",
    "RunResult",
    "RunStatus",
    "RunSummary",
    "RuntimeContext",
    "RuntimeContextVar",
    "RuntimeEvent",
    "RuntimeEventBus",
    "RuntimeMetrics",
    "TenantRequiredError",
    "TOOL_CALLED",
    "TOOL_DENIED",
    "ToolCall",
    "ToolDef",
    "ToolForbiddenError",
    "ToolRegistryPort",
    "ToolResult",
    "ToolSchema",
    "WorkflowFactory",
    "WorkflowResult",
    "WorkflowTypeNotFoundError",
    "WorkflowEnginePort",
    "current_context",
    "find_stale_runs",
    "get_tenant_id",
    "with_context",
]
