"""Layer 4 Agent Runtime — public package surface."""

from __future__ import annotations

from .adapters import LegacyToolRegistryAdapter, PolicyAuthzPort
from .context import RuntimeContextVar, current_context, get_tenant_id, with_context
from .core import AgentRuntimeImpl
from .errors import (
    AgentRuntimeError,
    CheckpointConflictError,
    ProviderNotFoundError,
    RunNotFoundError,
    TenantRequiredError,
    ToolForbiddenError,
    WorkflowTypeNotFoundError,
)
from .models import (
    AuthzDecision,
    Checkpoint,
    Message,
    ModelConfig,
    ModelResponse,
    ResumeRequest,
    RunEnvelope,
    RunRequest,
    RunResult,
    RunStatus,
    RunSummary,
    RuntimeContext,
    ToolCall,
    ToolDef,
    ToolResult,
    ToolSchema,
    WorkflowResult,
)
from .ports import (
    AgentRuntime,
    AuthzPort,
    CheckpointPort,
    MemoryPort,
    ModelProviderPort,
    ToolRegistryPort,
    WorkflowEnginePort,
    WorkflowFactory,
)

__all__ = [
    "AgentRuntime",
    "AgentRuntimeError",
    "AgentRuntimeImpl",
    "AuthzDecision",
    "AuthzPort",
    "Checkpoint",
    "CheckpointConflictError",
    "CheckpointPort",
    "LegacyToolRegistryAdapter",
    "Message",
    "ModelConfig",
    "ModelProviderPort",
    "ModelResponse",
    "MemoryPort",
    "PolicyAuthzPort",
    "ProviderNotFoundError",
    "ResumeRequest",
    "RunEnvelope",
    "RunNotFoundError",
    "RunRequest",
    "RunResult",
    "RunStatus",
    "RunSummary",
    "RuntimeContext",
    "RuntimeContextVar",
    "TenantRequiredError",
    "ToolCall",
    "ToolDef",
    "ToolForbiddenError",
    "ToolRegistryPort",
    "ToolResult",
    "ToolSchema",
    "WorkflowFactory",
    "WorkflowResult",
    "WorkflowTypeNotFoundError",
    "WorkflowEnginePort",
    "current_context",
    "get_tenant_id",
    "with_context",
]
