"""Provider verification for Layer 4 Agents API Pact contracts.

Replays consumer expectations (generated by the consumer tests) against the
real Layer 4 Agents API to confirm the provider satisfies all recorded
interactions.

Requires the Layer 4 service to be running.  In local development start it with:
    docker compose -f docker-compose.dev.yml up layer4-agents
    # or
    pnpm --dir apps/web run dev:live   # if layer4 is part of the live stack

Run verification:
    pytest tests/pact/test_l4_provider_verify.py -v

CI integration:
    Set CONTRACT_TEST_ENFORCE=1 to fail when the provider is unreachable.
    Set PACT_BROKER_URL to pull the latest published consumer contract instead
    of the local file.
"""

from __future__ import annotations

import os
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import pytest

pytestmark = [pytest.mark.pact, pytest.mark.service_required]


def _is_truthy(value: str | None) -> bool:
    if value is None:
        return False
    return value.strip().lower() in {"1", "true", "yes", "on"}


@pytest.fixture(scope="session")
def layer4_health_url(layer4_provider_url: str) -> str:
    return f"{layer4_provider_url}/health"


@pytest.fixture(scope="session")
def provider_is_reachable(layer4_health_url: str) -> bool:
    """Probe the provider health endpoint to decide if we can verify."""
    try:
        req = urllib.request.Request(layer4_health_url)
        with urllib.request.urlopen(req, timeout=2) as response:
            return response.status == 200
    except (urllib.error.URLError, ConnectionError, OSError):
        return False


@pytest.fixture
def pact_file_path(pact_dir: Path) -> Path:
    """Path to the consumer-generated pact file for Layer 4."""
    path = pact_dir / "value-fabric-frontend-layer4-agents-api.json"
    if not path.exists():
        pytest.skip(
            f"Pact file not found: {path}.\n"
            "Run consumer tests first:\n"
            "  pytest tests/pact/test_l4_consumer_contract.py -v"
        )
    return path


class TestL4ProviderPactVerification:
    """Verify Layer 4 provider against consumer Pact contracts."""

    @pytest.mark.pact
    def test_provider_verifies_consumer_contract(
        self,
        provider_is_reachable: bool,
        layer4_provider_url: str,
        pact_file_path: Path,
    ) -> None:
        """Replay all consumer interactions against the running Layer 4 API."""
        if not provider_is_reachable:
            if _is_truthy(os.getenv("CONTRACT_TEST_ENFORCE")) or _is_truthy(
                os.getenv("CI")
            ):
                pytest.fail(
                    f"Layer 4 provider is not reachable at {layer4_provider_url}.\n"
                    "Start the service before running provider verification."
                )
            pytest.skip(
                f"Layer 4 provider unreachable at {layer4_provider_url}. "
                "Start the service to run provider verification."
            )

        pytest.importorskip("pact")
        from pact import Verifier

        verifier = Verifier(
            provider="layer4-agents-api",
            provider_base_url=layer4_provider_url,
        )

        output, _ = verifier.verify_pacts(
            str(pact_file_path),
            verbose=False,
            provider_states_setup_url=None,
        )

        # The Ruby verifier returns a non-zero exit code on failure which
        # pact-python translates into a raised VerifierError.  If we reach
        # this line without an exception, the contract is satisfied.
        assert output == 0, f"Provider verification failed for {pact_file_path}"
