apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Service
      name: layer4-agents-active
    patch: |-
      - op: replace
        path: /spec/selector/track
        value: green
