---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: application
  namespace: value-fabric
spec:
  parentRefs:
    - name: value-fabric-gateway
      sectionName: https-frontend
  hostnames:
    - __HOST__
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /v1
      backendRefs:
        - name: api-gateway
          port: 8000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 3000
