apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-core-data
  namespace: value-fabric
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-encrypted
  resources:
    requests:
      storage: 50Gi
