"""Static seed finding catalog definitions mapping finding metadata to check functions."""

from __future__ import annotations

from typing import Any

from ..models import AuditArea, Confidence, Severity
from .catalog_checks import (
    _check_adr_gaps,
    _check_agents_md_audit_rules,
    _check_bare_excepts,
    _check_ci_timeouts,
    _check_conflicting_claims,
    _check_contract_drift,
    _check_coverage_config,
    _check_deep_nesting,
    _check_dependabot,
    _check_dependency_pinning,
    _check_duplicate_files,
    _check_fast_unit_marker,
    _check_graceful_shutdown,
    _check_hardcoded_secrets,
    _check_health_endpoints,
    _check_http_timeouts,
    _check_idempotency_gaps,
    _check_infisical_barrier,
    _check_llm_guardrails,
    _check_migration_downgrades,
    _check_missing_debug_config,
    _check_missing_repo_audit_skill,
    _check_missing_tier1_docs,
    _check_missing_tier2_docs,
    _check_missing_unit_tests,
    _check_mypy_disabled,
    _check_oversized_frontend,
    _check_oversized_python,
    _check_parallel_tests,
    _check_pr_template,
    _check_pydantic_v1,
    _check_pytest_timeouts,
    _check_relative_imports,
    _check_ruff_sprawl,
    _check_security_workflow,
    _check_service_boundaries,
    _check_skill_prompts_complete,
    _check_stale_runbooks,
    _check_test_skips,
    _check_todo_backlog,
    _check_tool_schema_completeness,
    _check_unvalidated_env,
    _check_workflow_secrets,
)

# ---------------------------------------------------------------------------
# Catalog definition
# ---------------------------------------------------------------------------

SEED_FINDINGS: list[dict[str, Any]] = [
    # Architecture
    {
        "id": "ARCH-001",
        "severity": Severity.HIGH,
        "confidence": Confidence.HIGH,
        "area": AuditArea.ARCHITECTURE,
        "effort": "L",
        "risk_of_change": "Medium",
        "owner": "Platform Architecture",
        "target_sprint": 1,
        "observed_fact": "Python modules exceed the recommended maximum line count.",
        "inference_risk": "Oversized modules concentrate complexity and slow reviews and testing.",
        "business_impact": "Slower delivery velocity and higher defect escape rate.",
        "recommended_fix": "Refactor large modules into smaller, single-responsibility modules.",
        "check": _check_oversized_python,
    },
    {
        "id": "ARCH-002",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.ARCHITECTURE,
        "effort": "M",
        "risk_of_change": "Low",
        "owner": "Frontend Platform",
        "target_sprint": 2,
        "observed_fact": "Frontend source files exceed the recommended line count.",
        "inference_risk": "Large components become difficult to test, compose, and reason about.",
        "business_impact": "UI changes take longer and regressions become more likely.",
        "recommended_fix": "Split large components and utility files by concern.",
        "check": _check_oversized_frontend,
    },
    {
        "id": "ARCH-003",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.ARCHITECTURE,
        "effort": "M",
        "risk_of_change": "Low",
        "owner": "Platform Architecture",
        "target_sprint": 2,
        "observed_fact": "Duplicate source files were detected by content hash.",
        "inference_risk": "Duplicate code increases maintenance burden and drift risk.",
        "business_impact": "Bug fixes must be applied in multiple places, risking inconsistency.",
        "recommended_fix": "Deduplicate into shared packages or utilities.",
        "check": _check_duplicate_files,
    },
    {
        "id": "ARCH-004",
        "severity": Severity.LOW,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.ARCHITECTURE,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Platform Architecture",
        "target_sprint": 3,
        "observed_fact": "Source files are nested deeper than eight directory levels.",
        "inference_risk": "Deep nesting signals poor package cohesion and discovery friction.",
        "business_impact": "New contributors struggle to locate relevant code.",
        "recommended_fix": "Flatten overly deep package trees and restructure by domain.",
        "check": _check_deep_nesting,
    },
    {
        "id": "ARCH-005",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.ARCHITECTURE,
        "effort": "L",
        "risk_of_change": "High",
        "owner": "Platform Architecture",
        "target_sprint": 1,
        "observed_fact": "Cross-layer imports violate the six-layer boundary policy.",
        "inference_risk": "Layer coupling undermines modularity and independent deployability.",
        "business_impact": "Changes in one layer can unexpectedly cascade into others.",
        "recommended_fix": "Route cross-layer calls through the API gateway or shared packages.",
        "check": _check_service_boundaries,
    },
    # Code Quality
    {
        "id": "CQ-001",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CODE_QUALITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Backend Guild",
        "target_sprint": 2,
        "observed_fact": "Relative imports are used extensively in Python packages.",
        "inference_risk": "Relative imports make refactoring and package relocation fragile.",
        "business_impact": "Renaming or moving packages creates churn and import errors.",
        "recommended_fix": "Convert relative imports to absolute canonical imports.",
        "check": _check_relative_imports,
    },
    {
        "id": "CQ-002",
        "severity": Severity.HIGH,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CODE_QUALITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Backend Guild",
        "target_sprint": 1,
        "observed_fact": "Bare ``except:`` clauses catch all exceptions indiscriminately.",
        "inference_risk": "Bare excepts hide programming errors and break error handling contracts.",
        "business_impact": "Bugs become harder to diagnose and may be silently swallowed.",
        "recommended_fix": "Replace bare excepts with specific exception types.",
        "check": _check_bare_excepts,
    },
    {
        "id": "CQ-003",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.CODE_QUALITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Backend Guild",
        "target_sprint": 2,
        "observed_fact": "mypy configuration disables strictness checks.",
        "inference_risk": "Disabled type checks allow type errors to reach production.",
        "business_impact": "Runtime type failures increase support load and incident frequency.",
        "recommended_fix": "Remove non-essential mypy overrides and address root causes.",
        "check": _check_mypy_disabled,
    },
    {
        "id": "CQ-004",
        "severity": Severity.LOW,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.CODE_QUALITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Backend Guild",
        "target_sprint": 3,
        "observed_fact": "ruff is configured to ignore a large number of lint rules.",
        "inference_risk": "Broad lint overrides hide maintainability and correctness issues.",
        "business_impact": "Technical debt accumulates faster than the linter can surface it.",
        "recommended_fix": "Tighten ruff ignore lists and resolve underlying issues incrementally.",
        "check": _check_ruff_sprawl,
    },
    {
        "id": "CQ-005",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CODE_QUALITY,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Backend Guild",
        "target_sprint": 4,
        "observed_fact": "A large backlog of TODO/FIXME/XXX/HACK comments remains in source.",
        "inference_risk": "Comment debt often signals deferred defects and design shortcuts.",
        "business_impact": "Known issues are forgotten until they surface in production.",
        "recommended_fix": "Convert actionable comments into tracked tickets and resolve them.",
        "check": _check_todo_backlog,
    },
    # Correctness
    {
        "id": "COR-001",
        "severity": Severity.HIGH,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.CORRECTNESS,
        "effort": "M",
        "risk_of_change": "Medium",
        "owner": "API Platform",
        "target_sprint": 1,
        "observed_fact": "OpenAPI contracts are not aligned with the number of service route groups.",
        "inference_risk": "Undocumented or mismatched contracts cause integration drift.",
        "business_impact": "Consumers break when route behavior changes without contract updates.",
        "recommended_fix": "Add or update OpenAPI specs for every route group and gate drift in CI.",
        "check": _check_contract_drift,
    },
    {
        "id": "COR-002",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CORRECTNESS,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Data Platform",
        "target_sprint": 2,
        "observed_fact": "Alembic migrations are missing downgrade functions.",
        "inference_risk": "Missing downgrades prevent safe rollback during failed deployments.",
        "business_impact": "Production incidents may require manual, error-prone recovery.",
        "recommended_fix": "Add downgrade functions to every migration or document exceptions.",
        "check": _check_migration_downgrades,
    },
    {
        "id": "COR-003",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.CORRECTNESS,
        "effort": "M",
        "risk_of_change": "Medium",
        "owner": "Backend Guild",
        "target_sprint": 2,
        "observed_fact": "Legacy pydantic v1 or ``Config`` patterns remain in the codebase.",
        "inference_risk": "Legacy patterns may be deprecated or incompatible with future upgrades.",
        "business_impact": "Upgrade paths become blocked, increasing migration cost.",
        "recommended_fix": "Migrate to pydantic v2 idioms and remove legacy config classes.",
        "check": _check_pydantic_v1,
    },
    {
        "id": "COR-004",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.CORRECTNESS,
        "effort": "M",
        "risk_of_change": "Medium",
        "owner": "Backend Guild",
        "target_sprint": 2,
        "observed_fact": "Environment variables are read directly without visible validation.",
        "inference_risk": "Missing validation leads to misconfiguration and runtime failures.",
        "business_impact": "Services may start with invalid config and fail silently or loudly.",
        "recommended_fix": "Centralize environment parsing through validated config models.",
        "check": _check_unvalidated_env,
    },
    {
        "id": "COR-005",
        "severity": Severity.HIGH,
        "confidence": Confidence.LOW,
        "area": AuditArea.CORRECTNESS,
        "effort": "L",
        "risk_of_change": "Medium",
        "owner": "API Platform",
        "target_sprint": 1,
        "observed_fact": "Mutating API endpoints do not mention idempotency controls.",
        "inference_risk": "Retry storms and partial failures can create duplicate side effects.",
        "business_impact": "Data corruption and inconsistent state can result from retries.",
        "recommended_fix": "Add idempotency keys to POST/PUT/PATCH endpoints and document behavior.",
        "check": _check_idempotency_gaps,
    },
    # Testing
    {
        "id": "TEST-001",
        "severity": Severity.HIGH,
        "confidence": Confidence.HIGH,
        "area": AuditArea.TESTING,
        "effort": "L",
        "risk_of_change": "Low",
        "owner": "Quality Engineering",
        "target_sprint": 1,
        "observed_fact": "Some services lack a populated ``tests/unit`` directory.",
        "inference_risk": "Untested services accumulate regression risk and slow refactoring.",
        "business_impact": "Production defects slip through because behavior is not verified.",
        "recommended_fix": "Add focused unit tests for every service entrypoint and pure function.",
        "check": _check_missing_unit_tests,
    },
    {
        "id": "TEST-002",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.TESTING,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Quality Engineering",
        "target_sprint": 2,
        "observed_fact": "pytest is not configured with a global timeout.",
        "inference_risk": "Hung tests can block CI pipelines indefinitely.",
        "business_impact": "Delayed feedback and wasted CI minutes reduce team velocity.",
        "recommended_fix": "Add pytest-timeout and a sensible default timeout to pytest options.",
        "check": _check_pytest_timeouts,
    },
    {
        "id": "TEST-003",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.TESTING,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Quality Engineering",
        "target_sprint": 2,
        "observed_fact": "No code coverage configuration is present.",
        "inference_risk": "Without coverage gating, untested code can merge unchecked.",
        "business_impact": "Regression risk grows as coverage gaps are not visible.",
        "recommended_fix": "Add coverage configuration and a CI gate for minimum coverage.",
        "check": _check_coverage_config,
    },
    {
        "id": "TEST-004",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.TESTING,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Quality Engineering",
        "target_sprint": 4,
        "observed_fact": "Test skips are used without a documented reason.",
        "inference_risk": "Unexplained skips hide broken or obsolete tests.",
        "business_impact": "Coverage gaps are not transparent and may mask regressions.",
        "recommended_fix": "Add a ``reason=`` to every pytest skip and review skipped tests.",
        "check": _check_test_skips,
    },
    {
        "id": "TEST-005",
        "severity": Severity.LOW,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.TESTING,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Quality Engineering",
        "target_sprint": 3,
        "observed_fact": "Test suite is not configured to run in parallel.",
        "inference_risk": "Sequential tests extend CI feedback loops and underutilize agents.",
        "business_impact": "Slower builds reduce developer iteration speed.",
        "recommended_fix": "Configure pytest-xdist and run tests with ``-n auto`` in CI.",
        "check": _check_parallel_tests,
    },
    # Security
    {
        "id": "SEC-001",
        "severity": Severity.CRITICAL,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.SECURITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Security",
        "target_sprint": 1,
        "observed_fact": "Potential hardcoded secrets or credential patterns were detected.",
        "inference_risk": "Committed credentials can be leaked and abused by attackers.",
        "business_impact": "Data breaches, unauthorized access, and compliance violations.",
        "recommended_fix": "Move secrets to a vault, rotate any exposed values, and add secret scanning.",
        "check": _check_hardcoded_secrets,
    },
    {
        "id": "SEC-002",
        "severity": Severity.HIGH,
        "confidence": Confidence.HIGH,
        "area": AuditArea.SECURITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Security",
        "target_sprint": 1,
        "observed_fact": "No dedicated security gates workflow is present.",
        "inference_risk": "Vulnerabilities and supply-chain risks are not blocked at merge time.",
        "business_impact": "Security issues reach production before detection.",
        "recommended_fix": "Add a security-gates workflow with dependency and secret scanning.",
        "check": _check_security_workflow,
    },
    {
        "id": "SEC-003",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.SECURITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Security",
        "target_sprint": 2,
        "observed_fact": "Many npm dependencies use caret or tilde version ranges.",
        "inference_risk": "Loose ranges allow unexpected package updates and supply-chain drift.",
        "business_impact": "A compromised upstream package can be pulled automatically.",
        "recommended_fix": "Pin dependency versions and use lockfile integrity checks.",
        "check": _check_dependency_pinning,
    },
    {
        "id": "SEC-004",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.LOW,
        "area": AuditArea.SECURITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Security",
        "target_sprint": 2,
        "observed_fact": "LLM prompt files do not contain obvious guardrail language.",
        "inference_risk": "Prompts without guardrails may be susceptible to injection or misuse.",
        "business_impact": "Agents could produce harmful, incorrect, or out-of-policy outputs.",
        "recommended_fix": "Add explicit guardrail and policy language to every LLM prompt.",
        "check": _check_llm_guardrails,
    },
    {
        "id": "SEC-005",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.SECURITY,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Security",
        "target_sprint": 3,
        "observed_fact": "Workflows reference repository secrets directly.",
        "inference_risk": "Broad secret usage increases blast radius if a workflow is compromised.",
        "business_impact": "Leaked workflows could expose production credentials.",
        "recommended_fix": "Scope secrets to the jobs that need them and audit usage regularly.",
        "check": _check_workflow_secrets,
    },
    # CI/CD
    {
        "id": "CICD-001",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CICD,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Platform Engineering",
        "target_sprint": 2,
        "observed_fact": "CI workflow jobs do not specify ``timeout-minutes``.",
        "inference_risk": "Jobs can hang indefinitely, blocking pipelines and consuming minutes.",
        "business_impact": "Longer incident recovery and inflated CI costs.",
        "recommended_fix": "Add ``timeout-minutes`` to every CI job.",
        "check": _check_ci_timeouts,
    },
    {
        "id": "CICD-002",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CICD,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Platform Engineering",
        "target_sprint": 3,
        "observed_fact": "No pull request template is present.",
        "inference_risk": "PRs may omit governance, security, and testing context.",
        "business_impact": "Lower review quality and inconsistent merge standards.",
        "recommended_fix": "Add a PR template with required governance checklists.",
        "check": _check_pr_template,
    },
    {
        "id": "CICD-003",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CICD,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Platform Engineering",
        "target_sprint": 3,
        "observed_fact": "Workflows directly consume repository secrets.",
        "inference_risk": "Direct secret use complicates rotation and auditability.",
        "business_impact": "Increased exposure if a workflow or action is compromised.",
        "recommended_fix": "Pass secrets via environments and limit workflow permissions.",
        "check": _check_workflow_secrets,
    },
    {
        "id": "CICD-004",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.CICD,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Platform Engineering",
        "target_sprint": 4,
        "observed_fact": "Dependabot is not configured for the repository.",
        "inference_risk": "Vulnerable dependencies are not discovered automatically.",
        "business_impact": "Known CVEs remain in production until manual review.",
        "recommended_fix": "Add a .github/dependabot.yml for Python and npm ecosystems.",
        "check": _check_dependabot,
    },
    # Reliability
    {
        "id": "REL-001",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.RELIABILITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "SRE",
        "target_sprint": 2,
        "observed_fact": "HTTP client calls omit explicit timeouts.",
        "inference_risk": "Calls can hang forever, exhausting workers and cascading failures.",
        "business_impact": "Outages propagate when downstream dependencies degrade.",
        "recommended_fix": "Add explicit timeouts to every external HTTP call.",
        "check": _check_http_timeouts,
    },
    {
        "id": "REL-002",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.RELIABILITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "SRE",
        "target_sprint": 2,
        "observed_fact": "Some services do not expose a ``/health`` endpoint.",
        "inference_risk": "Load balancers and orchestrators cannot detect unhealthy instances.",
        "business_impact": "Failed instances may continue to receive traffic.",
        "recommended_fix": "Add a lightweight health endpoint to every service.",
        "check": _check_health_endpoints,
    },
    {
        "id": "REL-003",
        "severity": Severity.LOW,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.RELIABILITY,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "SRE",
        "target_sprint": 4,
        "observed_fact": "RUNBOOK.md is missing or has not been updated recently.",
        "inference_risk": "Outdated runbooks slow incident response and increase recovery time.",
        "business_impact": "Longer outages and higher operational stress during incidents.",
        "recommended_fix": "Create or refresh RUNBOOK.md with current procedures.",
        "check": _check_stale_runbooks,
    },
    {
        "id": "REL-004",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.RELIABILITY,
        "effort": "S",
        "risk_of_change": "Medium",
        "owner": "SRE",
        "target_sprint": 2,
        "observed_fact": "Service entrypoints lack explicit graceful shutdown handlers.",
        "inference_risk": "In-flight requests may be dropped during deploys or restarts.",
        "business_impact": "User-facing errors and data inconsistency during rollouts.",
        "recommended_fix": "Register SIGTERM/SIGINT handlers and drain in-flight work.",
        "check": _check_graceful_shutdown,
    },
    # Documentation
    {
        "id": "DOC-001",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.DOCUMENTATION,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 3,
        "observed_fact": "Expected tier-1 governance documents are missing from the repository root.",
        "inference_risk": "Contributors lack authoritative guidance on process, security, and operations.",
        "business_impact": "Onboarding friction and inconsistent engineering practices.",
        "recommended_fix": "Add the missing root-level governance documents.",
        "check": _check_missing_tier1_docs,
    },
    {
        "id": "DOC-002",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.DOCUMENTATION,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 4,
        "observed_fact": "Expected tier-2 technical reference documents are missing.",
        "inference_risk": "Deep technical context is tribal knowledge rather than documented.",
        "business_impact": "Harder maintenance, slower incident response, and knowledge silos.",
        "recommended_fix": "Add missing reference docs for architecture, data model, and operations.",
        "check": _check_missing_tier2_docs,
    },
    {
        "id": "DOC-003",
        "severity": Severity.LOW,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.DOCUMENTATION,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 4,
        "observed_fact": "ADR numbering contains gaps in the expected sequence.",
        "inference_risk": "Missing ADRs suggest undocumented or reversed decisions.",
        "business_impact": "Decision history is incomplete, complicating audits and onboarding.",
        "recommended_fix": "Backfill missing ADRs or renumber to maintain a contiguous sequence.",
        "check": _check_adr_gaps,
    },
    {
        "id": "DOC-004",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.DOCUMENTATION,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 3,
        "observed_fact": "Documentation contains conflicting package manager guidance.",
        "inference_risk": "Conflicting instructions lead to inconsistent local setups and lockfile drift.",
        "business_impact": "New contributors hit setup issues and CI may use the wrong package manager.",
        "recommended_fix": "Standardize on pnpm everywhere and remove npm references.",
        "check": _check_conflicting_claims,
    },
    # Agent Readiness
    {
        "id": "AGENT-001",
        "severity": Severity.HIGH,
        "confidence": Confidence.HIGH,
        "area": AuditArea.AGENT_READINESS,
        "effort": "M",
        "risk_of_change": "Low",
        "owner": "Agent Platform",
        "target_sprint": 1,
        "observed_fact": "The ``repo-audit`` skill package is missing or incomplete.",
        "inference_risk": "The audit agent cannot be invoked as a portable skill by the agent harness.",
        "business_impact": "Audit capability is not reusable across workspaces and interfaces.",
        "recommended_fix": "Create .agent/skills/repo-audit with SKILL.md, config.yaml, and prompts.",
        "check": _check_missing_repo_audit_skill,
    },
    {
        "id": "AGENT-002",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.HIGH,
        "area": AuditArea.AGENT_READINESS,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Agent Platform",
        "target_sprint": 2,
        "observed_fact": "The ``repo-audit`` skill is missing expected prompt files.",
        "inference_risk": "LLM-powered phases of the audit agent cannot use consistent prompts.",
        "business_impact": "Agent output quality varies and is harder to govern.",
        "recommended_fix": "Add all required prompt files under .agent/skills/repo-audit/prompts.",
        "check": _check_skill_prompts_complete,
    },
    {
        "id": "AGENT-003",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.AGENT_READINESS,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Agent Platform",
        "target_sprint": 3,
        "observed_fact": "AGENTS.md does not reference the AuditOrchestrator or audit rules.",
        "inference_risk": "Agent fleet behavior is not documented or enforced for audit runs.",
        "business_impact": "Inconsistent agent behavior and missed governance checkpoints.",
        "recommended_fix": "Add audit agent triggers and rules to AGENTS.md.",
        "check": _check_agents_md_audit_rules,
    },
    {
        "id": "AGENT-004",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.AGENT_READINESS,
        "effort": "S",
        "risk_of_change": "Low",
        "owner": "Agent Platform",
        "target_sprint": 2,
        "observed_fact": "Tool schema files under .agent/tools are missing required fields.",
        "inference_risk": "The harness may reject tools or render them incorrectly.",
        "business_impact": "Agent capabilities are unavailable or behave unexpectedly.",
        "recommended_fix": "Validate every tool JSON against the required schema.",
        "check": _check_tool_schema_completeness,
    },
    # Dev Experience
    {
        "id": "DX-001",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.DEV_EXPERIENCE,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 4,
        "observed_fact": "No IDE debug configuration is present for the repository.",
        "inference_risk": "Developers must manually configure debugging, slowing troubleshooting.",
        "business_impact": "Longer debugging sessions and reduced developer productivity.",
        "recommended_fix": "Add a .vscode/launch.json or documented debugpy setup.",
        "check": _check_missing_debug_config,
    },
    {
        "id": "DX-002",
        "severity": Severity.MEDIUM,
        "confidence": Confidence.MEDIUM,
        "area": AuditArea.DEV_EXPERIENCE,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 3,
        "observed_fact": "Onboarding instructions depend on Infisical without a documented env fallback.",
        "inference_risk": "Contributors who cannot access Infisical cannot start the stack.",
        "business_impact": "Higher barrier to contribution and onboarding delays.",
        "recommended_fix": "Document a manual ``.env.example`` fallback path in AGENTS.md.",
        "check": _check_infisical_barrier,
    },
    {
        "id": "DX-003",
        "severity": Severity.LOW,
        "confidence": Confidence.HIGH,
        "area": AuditArea.DEV_EXPERIENCE,
        "effort": "XS",
        "risk_of_change": "Low",
        "owner": "Developer Experience",
        "target_sprint": 4,
        "observed_fact": "No ``unit`` pytest marker is configured for fast tests.",
        "inference_risk": "Developers cannot run a quick, isolated subset of tests locally.",
        "business_impact": "Slower local validation and wider CI feedback loops.",
        "recommended_fix": "Register a ``unit`` marker and provide a Makefile target for fast tests.",
        "check": _check_fast_unit_marker,
    },
]
