name: "Minimal API Changelog"

permissions:
  contents: read

"on":
  workflow_dispatch:
    inputs:
      from_ref:
        description: "Base ref"
        required: true
        default: ""
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: echo "hello ${{ github.event.inputs.from_ref }}"
