name: "Minimal Supply Chain"

permissions:
  contents: read

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello supply chain"
